"""
handoff.py — write a deterministic session-handoff skeleton (no model needed).

Used by context_watch.py to auto-write a handoff when the running context
estimate crosses the handoff threshold, and available as a CLI. The skeleton
captures only what can be gathered WITHOUT conversation context: git
branch/status/diff-stat/recent commits, the stored session task signature, the
running token estimate, and a timestamp. Because the hook (not the model) writes
it, a handoff is guaranteed to exist even if the session then dies — but it has
no decisions/next-steps narrative. A fresh session loads it on demand via the
/nx-load command; the user can run /nx-save for a richer version.

CLI:
  python3 handoff.py write --session <id> [--cwd <dir>] [--tokens <n>]

Fail-open: errors degrade to an empty/partial skeleton rather than raising, so a
hook calling this never breaks the turn.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import subprocess
import sys

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

import store  # noqa: E402 — after sys.path tweak


def _git(cwd: str, *args: str) -> str:
    """Run a git command in *cwd*, returning stripped stdout ('' on any error)."""
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=cwd or None,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if out.returncode != 0:
            return ""
        return out.stdout.strip()
    except Exception:
        return ""


def _humanize_task(raw: str | None) -> str:
    """Render the stored task signature into a readable line.

    context_watch stores the task as a packed JSON signature (keyword list with
    an optional ``__type__:`` marker), not free text. Best-effort unpack it;
    fall back to the raw string or a placeholder.
    """
    if not raw:
        return "(none recorded)"
    try:
        parts = json.loads(raw)
        if isinstance(parts, list):
            task_type = None
            keywords = []
            for p in parts:
                if isinstance(p, str) and p.startswith("__type__:"):
                    task_type = p[len("__type__:"):]
                else:
                    keywords.append(p)
            bits = []
            if task_type:
                bits.append(f"type: {task_type}")
            if keywords:
                bits.append("keywords: " + ", ".join(sorted(keywords)))
            return "; ".join(bits) if bits else "(none recorded)"
    except Exception:
        pass
    return str(raw)


def _indent_block(text: str, placeholder: str) -> str:
    """Return *text* as an indented code block, or a placeholder if empty."""
    text = (text or "").strip()
    if not text:
        return f"  {placeholder}"
    return "\n".join("    " + line for line in text.splitlines())


def build_skeleton(session_id: str, cwd: str, token_total: int = 0) -> str:
    """Build the handoff skeleton markdown from git + stored state."""
    cwd = cwd or os.getcwd()
    branch = _git(cwd, "rev-parse", "--abbrev-ref", "HEAD") or "(unknown)"
    status = _git(cwd, "status", "--short")
    diffstat = _git(cwd, "diff", "--stat")
    commits = _git(cwd, "log", "--oneline", "-5")
    task = _humanize_task(store.get_session_task(session_id))
    now = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
    k_tokens = round((token_total or 0) / 1000)

    return f"""# Handoff (auto-skeleton): {branch}

**Session:** {session_id}   **Branch:** {branch}   **Written:** {now}
**Why now:** context crossed the auto-handoff threshold (~{k_tokens}k tokens).
**Note:** Auto-generated by the nexum hook with NO conversation context — it has
git state but no decisions/next-steps narrative. For a richer handoff, run
`/nx-save` in the originating session before it ends.

## Task (recorded signature)
{task}

## Git state (at write time)
- Branch: `{branch}`
- Uncommitted changes (`git status --short`):
{_indent_block(status, "(working tree clean)")}
- Diff stat (`git diff --stat`):
{_indent_block(diffstat, "(no unstaged changes)")}
- Recent commits (`git log --oneline -5`):
{_indent_block(commits, "(no commits)")}

## How to resume
- Run `git status` and `git diff` to see in-progress work.
- Open the files listed in the diff stat above first.
- This is a skeleton: reconstruct intent from the diff + task signature, or ask
  the user for the goal if it is unclear.
"""


def write_skeleton(
    session_id: str,
    data_dir: str | None = None,
    cwd: str | None = None,
    token_total: int = 0,
) -> str | None:
    """Write the skeleton to handoff/<session>.md and handoff/latest.md.

    Returns the per-session file path, or None on failure (fail-open).
    """
    try:
        data_dir = data_dir or store.nexum_data_dir()
        handoff_dir = os.path.join(data_dir, "handoff")
        os.makedirs(handoff_dir, exist_ok=True)
        content = build_skeleton(session_id, cwd or os.getcwd(), token_total)
        per_session = os.path.join(handoff_dir, f"{session_id}.md")
        latest = os.path.join(handoff_dir, "latest.md")
        for path in (per_session, latest):
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
        return per_session
    except Exception:
        return None


def _cmd_write(args) -> None:
    path = write_skeleton(
        session_id=args.session,
        cwd=args.cwd,
        token_total=args.tokens or 0,
    )
    print(json.dumps({"ok": path is not None, "path": path}))


def main() -> None:
    parser = argparse.ArgumentParser(prog="handoff.py", description="Nexum handoff skeleton writer.")
    sub = parser.add_subparsers(dest="command")
    p_write = sub.add_parser("write", help="Write the handoff skeleton for a session.")
    p_write.add_argument("--session", required=True)
    p_write.add_argument("--cwd", default=None)
    p_write.add_argument("--tokens", type=int, default=0)

    args = parser.parse_args()
    if args.command == "write":
        _cmd_write(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
